# This is a basic workflow to help you get started with Actions

name: Deploy and Test on PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

env:
  DBT_PROFILE_TARGET: default
  DBT_PROFILE_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_PROFILE_SNOWFLAKE_ACCOUNT }}
  DBT_PROFILE_USER: ${{ secrets.DBT_PROFILE_DEFAULT_USER }}
  DBT_PROFILE_PASSWORD: ${{ secrets.DBT_PROFILE_DEFAULT_PASSWORD }}
  DBT_PROFILE_ROLE: TRANSFORMER
  DBT_PROFILE_DB: ${{ secrets.DBT_PRFILE_DEFAULT_DB }}
  DBT_PROFILE_SCHEMA: STAGING
  DBT_PROFILE_WH: TRANSFORMING

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout branch
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Install Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      - name: Install DBT
        run: |
          python -m pip install --upgrade pip
          pip install dbt
          
      - name: Deploy
        run: |
          dbt run --profiles-dir ./ci_profiles
          dbt test --profiles-dir ./ci_profiles
