version: 2
models:
  - name: customers
    description: '{{ doc("all_about_customers") }}'
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when the customer has yet to place an order.

  - name: stg_customers
    description: This model cleans up the customer data
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: This model cleans up the order data
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id